"""
Civic Desk Ticket Bank — 53 Diverse Civic Service Scenarios.

Each ticket contains:
  - ticket_id:             Unique identifier (TKT-1xx through TKT-5xx)
  - description:           The citizen's complaint / report
  - policy_snippet:        Relevant municipal policy the AI should apply
  - active_resources:      Currently available crews / assets
  - difficulty_level:      easy | medium | hard | ambiguous
  - expected_queue:        Correct routing target
  - expected_priority:     Correct urgency level
  - expected_action_type:  Route | Request_Info | Escalate | Resolve
  - policy_keywords:       Terms used for justification keyword scoring
"""

from typing import List, Dict, Any

#                           EASY Tickets  (~15)
_EASY: List[Dict[str, Any]] = [
    {
        "ticket_id": "TKT-101",
        "description": "Large tree branch fell on Main Street, blocking the right lane.",
        "policy_snippet": "All road blockages are High priority and belong to Public_Works.",
        "active_resources": "Public Works Team A is available.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["blockage", "road", "public works", "tree", "branch"],
    },
    {
        "ticket_id": "TKT-102",
        "description": "Pothole approximately 2 feet wide on 5th Avenue near the school zone.",
        "policy_snippet": "Road surface damage in school zones is High priority for Public_Works.",
        "active_resources": "Road Repair Crew B on standby.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["pothole", "road", "school zone", "surface damage"],
    },
    {
        "ticket_id": "TKT-103",
        "description": "Overflowing public trash can at Central Park, waste spilling onto walkway.",
        "policy_snippet": "Overflowing waste receptacles are Medium priority under Sanitation.",
        "active_resources": "Sanitation Truck 7 available in District 3.",
        "difficulty_level": "easy",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["trash", "waste", "overflow", "sanitation", "receptacle"],
    },
    {
        "ticket_id": "TKT-104",
        "description": "Streetlight out on Oak Boulevard between 3rd and 4th Street.",
        "policy_snippet": "Non-functional streetlights are Medium priority for Public_Works.",
        "active_resources": "Electrical Crew C available.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["streetlight", "light", "electrical", "public works"],
    },
    {
        "ticket_id": "TKT-105",
        "description": "Fire hydrant on Elm Street is leaking water steadily.",
        "policy_snippet": "Leaking hydrants are High priority for the Water department.",
        "active_resources": "Water Maintenance Unit 2 on call.",
        "difficulty_level": "easy",
        "expected_queue": "Water",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["hydrant", "leak", "water", "maintenance"],
    },
    {
        "ticket_id": "TKT-106",
        "description": "Graffiti spray-painted on the side of the public library building.",
        "policy_snippet": "Graffiti and vandalism on public property is Low priority for Public_Works.",
        "active_resources": "Graffiti removal team available next business day.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "Low",
        "expected_action_type": "Route",
        "policy_keywords": ["graffiti", "vandalism", "public property"],
    },
    {
        "ticket_id": "TKT-107",
        "description": "Illegal dumping of old furniture and mattresses in alley behind 200 Pine St.",
        "policy_snippet": "Illegal dumping complaints are Medium priority for Sanitation.",
        "active_resources": "Bulk Collection Unit available.",
        "difficulty_level": "easy",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["dumping", "illegal", "bulk", "sanitation", "waste"],
    },
    {
        "ticket_id": "TKT-108",
        "description": "Broken bench in Riverside Park playground area.",
        "policy_snippet": "Park furniture damage is Low priority for Public_Works unless safety hazard.",
        "active_resources": "Parks maintenance crew available.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "Low",
        "expected_action_type": "Route",
        "policy_keywords": ["bench", "park", "furniture", "maintenance"],
    },
    {
        "ticket_id": "TKT-109",
        "description": "Storm drain clogged with leaves on Walnut Street, causing minor pooling.",
        "policy_snippet": "Clogged drains are Medium priority for Water department.",
        "active_resources": "Drain clearing crew available.",
        "difficulty_level": "easy",
        "expected_queue": "Water",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["drain", "clog", "water", "storm", "pooling"],
    },
    {
        "ticket_id": "TKT-110",
        "description": "Stop sign knocked over at the corner of Birch and Maple.",
        "policy_snippet": "Downed traffic signs are High priority for Public_Works due to accident risk.",
        "active_resources": "Sign installation crew available.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["sign", "traffic", "accident risk", "public works"],
    },
    {
        "ticket_id": "TKT-111",
        "description": "Dead animal on the shoulder of Route 9 near mile marker 15.",
        "policy_snippet": "Animal carcass removal on roads is Medium priority for Sanitation.",
        "active_resources": "Animal control / sanitation unit en route.",
        "difficulty_level": "easy",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["animal", "carcass", "removal", "sanitation"],
    },
    {
        "ticket_id": "TKT-112",
        "description": "Water main break on Jefferson Avenue — water gushing from street.",
        "policy_snippet": "Water main breaks are Critical priority for the Water department.",
        "active_resources": "Emergency Water Response Team on standby.",
        "difficulty_level": "easy",
        "expected_queue": "Water",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["water main", "break", "critical", "emergency"],
    },
    {
        "ticket_id": "TKT-113",
        "description": "Noise complaint: loud music from a house party at 1 AM on a weekday.",
        "policy_snippet": "Noise violations after 10 PM on weekdays are Medium priority for Police.",
        "active_resources": "Patrol Unit 5 available in the area.",
        "difficulty_level": "easy",
        "expected_queue": "Police",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["noise", "violation", "police", "complaint"],
    },
    {
        "ticket_id": "TKT-114",
        "description": "Shopping cart abandoned in the middle of a residential sidewalk.",
        "policy_snippet": "Abandoned obstructions on sidewalks are Low priority for Public_Works.",
        "active_resources": "Public Works pickup crew available.",
        "difficulty_level": "easy",
        "expected_queue": "Public_Works",
        "expected_priority": "Low",
        "expected_action_type": "Route",
        "policy_keywords": ["obstruction", "sidewalk", "abandoned", "public works"],
    },
    {
        "ticket_id": "TKT-115",
        "description": "Recycling bin not collected on scheduled pickup day at 450 Cedar Lane.",
        "policy_snippet": "Missed collections are Low priority for Sanitation — schedule re-pickup.",
        "active_resources": "Recycling truck route resuming tomorrow.",
        "difficulty_level": "easy",
        "expected_queue": "Sanitation",
        "expected_priority": "Low",
        "expected_action_type": "Route",
        "policy_keywords": ["recycling", "collection", "missed", "sanitation"],
    },
]

#                          MEDIUM Tickets  (~20)
_MEDIUM: List[Dict[str, Any]] = [
    {
        "ticket_id": "TKT-201",
        "description": "Abandoned vehicle leaking fluid onto residential street near a playground.",
        "policy_snippet": "Abandoned vehicles with fluid leaks near sensitive areas require Police tow AND Sanitation hazmat cleanup.",
        "active_resources": "Police Tow Unit available; Hazmat Sanitation crew on 2-hour delay.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["abandoned", "vehicle", "fluid", "leak", "hazmat", "playground", "tow"],
    },
    {
        "ticket_id": "TKT-202",
        "description": "Construction noise from a building site at 2 AM in a residential zone.",
        "policy_snippet": "Construction is prohibited 9 PM–7 AM in residential zones; violations are High priority for Police enforcement.",
        "active_resources": "Code Enforcement Officer available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["construction", "noise", "violation", "residential", "prohibited", "enforcement"],
    },
    {
        "ticket_id": "TKT-203",
        "description": "Large sinkhole forming on a quiet residential street, about 3 feet deep.",
        "policy_snippet": "Sinkholes are Critical for Public_Works; check for water/sewer line involvement with Water dept.",
        "active_resources": "Emergency road crew and Water inspection team available.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["sinkhole", "critical", "road", "water", "sewer", "emergency"],
    },
    {
        "ticket_id": "TKT-204",
        "description": "Homeless encampment with open fire near a city bridge underpass.",
        "policy_snippet": "Encampments with fire hazards are High priority for Police (safety) with social services referral.",
        "active_resources": "Community Outreach Officer and Fire Prevention Unit available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["encampment", "fire", "hazard", "safety", "police", "outreach"],
    },
    {
        "ticket_id": "TKT-205",
        "description": "Sewage smell coming from storm drains after heavy rainfall on Park Avenue.",
        "policy_snippet": "Cross-contamination of storm and sewer systems is High priority for Water department.",
        "active_resources": "Sewer inspection team available.",
        "difficulty_level": "medium",
        "expected_queue": "Water",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["sewage", "storm drain", "contamination", "water", "sewer"],
    },
    {
        "ticket_id": "TKT-206",
        "description": "Traffic light stuck on red in all directions at the intersection of 1st and Main.",
        "policy_snippet": "Malfunctioning traffic signals are Critical priority for Public_Works; dispatch Police for traffic control.",
        "active_resources": "Traffic engineering crew available; Patrol Unit nearby.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["traffic light", "malfunction", "critical", "signal", "intersection"],
    },
    {
        "ticket_id": "TKT-207",
        "description": "Rat infestation reported in multiple houses along the 300 block of Vine Street.",
        "policy_snippet": "Multi-property pest infestations are High priority for Sanitation (vector control).",
        "active_resources": "Vector control team available.",
        "difficulty_level": "medium",
        "expected_queue": "Sanitation",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["rat", "infestation", "pest", "vector control", "sanitation"],
    },
    {
        "ticket_id": "TKT-208",
        "description": "Power lines sagging dangerously low over a school bus stop.",
        "policy_snippet": "Sagging power lines near schools/bus stops are Critical — route to Public_Works and notify utility company.",
        "active_resources": "Utility coordination liaison and emergency crew available.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["power lines", "sagging", "school", "critical", "utility", "safety"],
    },
    {
        "ticket_id": "TKT-209",
        "description": "Person reported selling counterfeit goods near the farmer's market.",
        "policy_snippet": "Counterfeit goods sales are Medium priority for Police commercial crimes unit.",
        "active_resources": "Commercial crimes detective available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["counterfeit", "goods", "police", "commercial", "crimes"],
    },
    {
        "ticket_id": "TKT-210",
        "description": "Broken water meter continuously running at 780 Chestnut Drive — resident reports spike in bill.",
        "policy_snippet": "Malfunctioning meters are Medium priority for Water department; verify before crediting.",
        "active_resources": "Meter technician available.",
        "difficulty_level": "medium",
        "expected_queue": "Water",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["meter", "malfunction", "water", "billing", "verify"],
    },
    {
        "ticket_id": "TKT-211",
        "description": "Crowd gathering for an unpermitted block party, blocking both lanes on Spruce Street.",
        "policy_snippet": "Unpermitted gatherings blocking traffic are High priority for Police; Public_Works for barricade support.",
        "active_resources": "Patrol Unit 12 and Public Works barricade team available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["unpermitted", "gathering", "blocking", "traffic", "police"],
    },
    {
        "ticket_id": "TKT-212",
        "description": "Suspected gas leak smell near a construction site on Oak Boulevard.",
        "policy_snippet": "Suspected gas leaks are Critical priority — route to Public_Works for utility coordination and Police for evacuation.",
        "active_resources": "Gas utility emergency line contacted; Police evacuation unit on standby.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["gas leak", "critical", "utility", "evacuation", "construction"],
    },
    {
        "ticket_id": "TKT-213",
        "description": "Flooding in residential basement due to backed-up city sewer line.",
        "policy_snippet": "Sewer backups causing property flooding are High priority for Water department.",
        "active_resources": "Sewer emergency crew available.",
        "difficulty_level": "medium",
        "expected_queue": "Water",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["flooding", "sewer", "backup", "water", "emergency"],
    },
    {
        "ticket_id": "TKT-214",
        "description": "Exposed rebar and crumbling concrete on a pedestrian footbridge over the creek.",
        "policy_snippet": "Structural defects on pedestrian bridges are High priority for Public_Works — assess for closure.",
        "active_resources": "Structural inspection team available.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["structural", "bridge", "defect", "safety", "inspection", "closure"],
    },
    {
        "ticket_id": "TKT-215",
        "description": "Multiple shopping carts dumped in the creek bed at Memorial Park.",
        "policy_snippet": "Debris in waterways is Medium priority — Sanitation for removal, Water for contamination check.",
        "active_resources": "Sanitation debris crew available.",
        "difficulty_level": "medium",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["debris", "waterway", "creek", "sanitation", "removal"],
    },
    {
        "ticket_id": "TKT-216",
        "description": "Ice cream truck parked and operating in a no-vending zone near the school.",
        "policy_snippet": "Vending violations in school zones are Medium priority for Police.",
        "active_resources": "Parking enforcement available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["vending", "violation", "school zone", "police", "enforcement"],
    },
    {
        "ticket_id": "TKT-217",
        "description": "Playground equipment with exposed sharp metal edges at Lincoln Park.",
        "policy_snippet": "Playground safety hazards are High priority for Public_Works — cordon area immediately.",
        "active_resources": "Parks safety crew available.",
        "difficulty_level": "medium",
        "expected_queue": "Public_Works",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["playground", "safety", "hazard", "sharp", "cordon"],
    },
    {
        "ticket_id": "TKT-218",
        "description": "Resident reports brown/discolored tap water at 55 Cypress Lane.",
        "policy_snippet": "Discolored water reports require Water department investigation — Medium priority.",
        "active_resources": "Water quality testing team available.",
        "difficulty_level": "medium",
        "expected_queue": "Water",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["discolored", "water", "quality", "testing", "investigation"],
    },
    {
        "ticket_id": "TKT-219",
        "description": "Feral cat colony growing near outdoor dining area of restaurants on Market Street.",
        "policy_snippet": "Feral animal colonies near food establishments are Medium priority for Sanitation (animal control).",
        "active_resources": "Animal control unit available.",
        "difficulty_level": "medium",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Route",
        "policy_keywords": ["feral", "animal", "colony", "sanitation", "control"],
    },
    {
        "ticket_id": "TKT-220",
        "description": "Street racing reported on Industrial Parkway at night, tire marks everywhere.",
        "policy_snippet": "Street racing is High priority for Police — deploy speed enforcement and investigation.",
        "active_resources": "Traffic enforcement unit and patrol available.",
        "difficulty_level": "medium",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["street racing", "speed", "enforcement", "police", "investigation"],
    },
]

#                            HARD Tickets  (~10)
_HARD: List[Dict[str, Any]] = [
    {
        "ticket_id": "TKT-301",
        "description": "Sinkhole opened on Elm Street directly above a water main — water bubbling up from the crack.",
        "policy_snippet": "Sinkholes with confirmed water infrastructure involvement are Critical for Water (lead dept) with Public_Works support for road closure.",
        "active_resources": "Water emergency team and road closure crew available.",
        "difficulty_level": "hard",
        "expected_queue": "Water",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["sinkhole", "water main", "critical", "infrastructure", "road closure", "emergency"],
    },
    {
        "ticket_id": "TKT-302",
        "description": "Large protest march blocking the intersection of Broadway and 5th, some demonstrators on the roadway.",
        "policy_snippet": "Permitted protests require Police monitoring; if unpermitted and blocking traffic, High priority Police response with Public_Works traffic support.",
        "active_resources": "Crowd management unit and traffic control team available.",
        "difficulty_level": "hard",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["protest", "crowd", "traffic", "police", "blocking", "public safety"],
    },
    {
        "ticket_id": "TKT-303",
        "description": "Chemical drums found illegally dumped behind an abandoned warehouse near the river.",
        "policy_snippet": "Hazardous material dumping near water sources is Critical — Sanitation hazmat lead, Water for contamination testing, Police for criminal investigation.",
        "active_resources": "Hazmat response team, water testing unit, and detective on call.",
        "difficulty_level": "hard",
        "expected_queue": "Sanitation",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["chemical", "hazardous", "dumping", "hazmat", "contamination", "criminal", "critical"],
    },
    {
        "ticket_id": "TKT-304",
        "description": "Bridge deck cracking observed on the Main Street overpass during routine patrol — heavy truck traffic.",
        "policy_snippet": "Structural bridge concerns with active heavy traffic are Critical for Public_Works — immediate engineering assessment and possible weight restriction.",
        "active_resources": "Structural engineer and traffic management team available.",
        "difficulty_level": "hard",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["bridge", "structural", "cracking", "critical", "engineering", "weight restriction"],
    },
    {
        "ticket_id": "TKT-305",
        "description": "Burst sewage pipe flooding a school parking lot during school hours.",
        "policy_snippet": "Sewage emergencies at schools are Critical for Water department — coordinate with school admin for evacuation if necessary.",
        "active_resources": "Emergency sewer repair crew and school liaison available.",
        "difficulty_level": "hard",
        "expected_queue": "Water",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["sewage", "burst", "school", "critical", "emergency", "evacuation"],
    },
    {
        "ticket_id": "TKT-306",
        "description": "Train derailment blocking 3 city streets, possible fuel spill from locomotive.",
        "policy_snippet": "Multi-street closures with hazmat risk are Critical — Police for perimeter, Public_Works for road management, Sanitation hazmat for spill. Escalate to Emergency Management.",
        "active_resources": "All emergency units mobilized.",
        "difficulty_level": "hard",
        "expected_queue": "Police",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["derailment", "hazmat", "fuel spill", "critical", "emergency management", "perimeter"],
    },
    {
        "ticket_id": "TKT-307",
        "description": "Apartment complex reports complete loss of water pressure across all 8 buildings.",
        "policy_snippet": "Multi-building water outages are Critical for Water — investigate main line failure and coordinate temporary water supply.",
        "active_resources": "Water distribution team and emergency supply tanker available.",
        "difficulty_level": "hard",
        "expected_queue": "Water",
        "expected_priority": "Critical",
        "expected_action_type": "Route",
        "policy_keywords": ["water pressure", "outage", "critical", "main line", "temporary supply"],
    },
    {
        "ticket_id": "TKT-308",
        "description": "Landslide blocking a hillside road and threatening homes below during ongoing storm.",
        "policy_snippet": "Active landslides are Critical for Public_Works with Police for evacuation and Water for drainage assessment.",
        "active_resources": "Heavy equipment crew, evacuation unit, and drainage team available.",
        "difficulty_level": "hard",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["landslide", "critical", "evacuation", "drainage", "emergency", "road closure"],
    },
    {
        "ticket_id": "TKT-309",
        "description": "Multiple reports of a large aggressive dog chasing pedestrians near the elementary school.",
        "policy_snippet": "Aggressive animals near schools are High priority for Police (public safety) with animal control support.",
        "active_resources": "Animal control officer and patrol unit nearby.",
        "difficulty_level": "hard",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["aggressive", "animal", "school", "police", "safety", "public safety"],
    },
    {
        "ticket_id": "TKT-310",
        "description": "Widespread power outage affecting 12 blocks downtown — traffic lights out, businesses closing.",
        "policy_snippet": "Major power outages are Critical for Public_Works (utility coordination) with Police for traffic control at uncontrolled intersections.",
        "active_resources": "Utility liaison, traffic officers, and emergency generators available.",
        "difficulty_level": "hard",
        "expected_queue": "Public_Works",
        "expected_priority": "Critical",
        "expected_action_type": "Escalate",
        "policy_keywords": ["power outage", "critical", "utility", "traffic control", "emergency"],
    },
]

#                       AMBIGUOUS / LOW-INFO Tickets  (~8)
_AMBIGUOUS: List[Dict[str, Any]] = [
    {
        "ticket_id": "TKT-401",
        "description": "Something is leaking on the road near my house.",
        "policy_snippet": "Unidentified leaks could be water, sewer, or vehicle fluid — request more info before routing.",
        "active_resources": "General inspection unit available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Water",
        "expected_priority": "Medium",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["leak", "unidentified", "request info", "inspection"],
    },
    {
        "ticket_id": "TKT-402",
        "description": "Bad smell near the park.",
        "policy_snippet": "Odor complaints may be sewer, sanitation, or industrial — requires investigation to determine source.",
        "active_resources": "Environmental inspector available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Sanitation",
        "expected_priority": "Medium",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["odor", "smell", "investigation", "source", "request info"],
    },
    {
        "ticket_id": "TKT-403",
        "description": "There's a big hole in the ground somewhere on Willow Street.",
        "policy_snippet": "Vague reports of ground depression need clarification: exact location, size, and any visible utilities.",
        "active_resources": "Inspection crew available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Public_Works",
        "expected_priority": "Medium",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["hole", "ground", "clarification", "location", "request info"],
    },
    {
        "ticket_id": "TKT-404",
        "description": "Kids are doing something dangerous at the intersection.",
        "policy_snippet": "Vague safety calls at intersections need clarification: nature of activity, number of people, and if traffic is affected.",
        "active_resources": "Community patrol available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Police",
        "expected_priority": "Medium",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["safety", "intersection", "clarification", "request info"],
    },
    {
        "ticket_id": "TKT-405",
        "description": "Water is everywhere on my block but I'm not sure where it's coming from.",
        "policy_snippet": "Unlocalized water on surface could be hydrant, main break, or storm overflow — request specific address and photos.",
        "active_resources": "Water inspection team available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Water",
        "expected_priority": "Medium",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["water", "unlocalized", "request info", "photos", "address"],
    },
    {
        "ticket_id": "TKT-406",
        "description": "Someone left a bunch of stuff on the corner.",
        "policy_snippet": "Unclear whether abandoned property, illegal dumping, or legitimate placement — request description and photos.",
        "active_resources": "General services available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Sanitation",
        "expected_priority": "Low",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["abandoned", "stuff", "unclear", "request info", "description"],
    },
    {
        "ticket_id": "TKT-407",
        "description": "Road is bumpy.",
        "policy_snippet": "Non-specific road complaints need exact location and severity assessment before dispatch.",
        "active_resources": "Road survey team available.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Public_Works",
        "expected_priority": "Low",
        "expected_action_type": "Request_Info",
        "policy_keywords": ["road", "bumpy", "location", "severity", "request info"],
    },
    {
        "ticket_id": "TKT-408",
        "description": "I think I heard gunshots but it might have been fireworks near the community center.",
        "policy_snippet": "Possible gunfire reports require immediate Police dispatch regardless of uncertainty — officer determines on scene.",
        "active_resources": "Patrol units available in the area.",
        "difficulty_level": "ambiguous",
        "expected_queue": "Police",
        "expected_priority": "High",
        "expected_action_type": "Route",
        "policy_keywords": ["gunfire", "fireworks", "police", "immediate", "dispatch", "safety"],
    },
]


# Master list 
TICKET_BANK: List[Dict[str, Any]] = _EASY + _MEDIUM + _HARD + _AMBIGUOUS


def get_ticket_by_id(ticket_id: str) -> Dict[str, Any] | None:
    """Return a single ticket dict by its ticket_id, or None if not found."""
    for ticket in TICKET_BANK:
        if ticket["ticket_id"] == ticket_id:
            return ticket
    return None


def get_tickets_by_difficulty(difficulty: str) -> List[Dict[str, Any]]:
    """Return all tickets that match the given difficulty level."""
    return [t for t in TICKET_BANK if t["difficulty_level"] == difficulty]


if __name__ == "__main__":
    print(f"Total tickets in bank: {len(TICKET_BANK)}")
    for d in ("easy", "medium", "hard", "ambiguous"):
        print(f"  {d:>10}: {len(get_tickets_by_difficulty(d))}")
